### ISSUE TITLE
Hifiasm as assembler

### ISSUE THREAD

**Issue by LYC-vio** [ptrebert/project-diploid-assembly#14]
Hi,

Thank you for developing this amazing pipeline! I've noticed that PGAS was motioned in a recently published paper [Pangenome-based genome inference allows efficient and accurate genotyping across a wide spectrum of variant classes](https://www.nature.com/articles/s41588-022-01043-w#additional-information), where they used:
> a development version of the PGAS pipeline (parameter settings v.13)

which:
> employed hifiasm v.0.15.2 as default assembler

However, I didn't find any information about hifiasm or "parameter settings v.13" in this repository. Would you please give me some suggestions?

Best regards

**Comment by ptrebert** [comment]
Hi,
there is a dev release tagged for the version of PGAS that was used in the PanGenie paper.
Best,
Peter
