### ISSUE TITLE
kmer analysis

### ISSUE THREAD

**Issue by ptrebert** [ptrebert/project-diploid-assembly#5]
add to pipeline
- lighter?
- bifrost

hg38 - phased assembly - Illumina reads

**Comment by tobiasmarschall** [comment]
Since working with reads directly when you last tried it, we could just use the proven recipe of lighter then bcalm and feed this into Bifrost as an assembly.

**Comment by ptrebert** [comment]
example code/rules for kmer analysis part of master now in dev/eval module `run_kmer_analysis.smk`
